#!/bin/bash
# Полная очистка конфигураций, данных code-server и остановка сервиса

main() {
    username="$1"
    if [ -z "$username" ]; then
        username=${whoami}
    fi
    read -p "Are you sure you want to clean up $username code-server? This will stop the service. [y/N]: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Cleaning up code-server data and configurations"

        if sudo -u $username \
                    XDG_RUNTIME_DIR="/run/user/$uid" \
                    DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$uid/bus" \
                    systemctl --user daemon-reload 2>/dev/null; then
            sudo -u $username \
                XDG_RUNTIME_DIR="/run/user/$uid" \
                DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$uid/bus" \
                systemctl --user stop "code-server.service" 2>/dev/null || true

            sudo -u $username \
                XDG_RUNTIME_DIR="/run/user/$uid" \
                DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$uid/bus" \
                systemctl --user disable "code-server.service" 2>/dev/null || true
        fi

        sudo -u $username \
            XDG_RUNTIME_DIR="/run/user/$uid" \
            DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$uid/bus" \
            rm -f "/home/$username/.config/systemd/user/code-server.service"
        sudo -u $username \
            XDG_RUNTIME_DIR="/run/user/$uid" \
            DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$uid/bus" \
            rm -f "/home/$username/.config/systemd/user/default.target.wants/code-server.service"

        sudo -u $username \
            XDG_RUNTIME_DIR="/run/user/$uid" \
            DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$uid/bus" \
            rm -f "/home/$username/.user-auto-code-server-guide.md" 2>/dev/null || true

        sudo -u $username \
            XDG_RUNTIME_DIR="/run/user/$uid" \
            DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$uid/bus" \
            rm -rf "/home/$username/.config/code-server" 2>/dev/null || true
        sudo -u $username \
            XDG_RUNTIME_DIR="/run/user/$uid" \
            DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$uid/bus" \
            rm -rf "/home/$username/.local/share/code-server" 2>/dev/null || true

        sudo -u $username \
            XDG_RUNTIME_DIR="/run/user/$uid" \
            DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$uid/bus" \
            systemctl daemon-reload

        echo "Cleanup completed"
    fi
}

main "$@"
